import {categories,countries,statusNames,esc,safeUrl,dateInZone,liveStatus,dueLabel,calendarCells,writingPrompt,outline} from './modules/domain.js';
import {loadEnvelope,storeEnvelope,newEnvelope,openEnvelope,encrypt} from './modules/vault.js';
import {registerPublicTools} from './modules/agent-tools.js';
const $=s=>document.querySelector(s), main=$('#main'), modal=$('#modal');
let feed={jobs:[],sources:[],changes:[],generatedAt:null}, personal=null, vaultKey=null, vaultSalt=null;
let filters={q:'',category:'',status:'active',country:''}, calendarDate=new Date(), editorId=null, editorJob=null, dirty=false, pendingAction=null, saving=Promise.resolve();
const uid=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const stamp=v=>v?new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'아직 없음';
const route=()=>location.hash.slice(1)||'domestic';
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4500);}
function showModal(html){$('#modal-content').innerHTML=html;if(!modal.open)modal.showModal();}
function closeModal(){modal.close();$('#modal-content').replaceChildren();pendingAction=null;}
$('#close-modal').onclick=closeModal;
modal.addEventListener('close',()=>{if(!modal.open){pendingAction=null;$('#modal-content').replaceChildren();}});
function header(title,desc='',action=''){return `<div class="page-head"><div><div class="eyebrow">QUANT CAREER DESK</div><h1>${esc(title)}</h1><p class="muted">${esc(desc)}</p></div>${action}</div>`;}
function syncVaultUi(){ $('#vault-status').textContent=personal?'로컬 보관함 열림':'보관함 잠김';$('#vault-button').textContent=personal?'보관함 잠그기':'로컬 보관함 열기'; }
async function persist(){const snapshot=structuredClone(personal),key=vaultKey,salt=vaultSalt;if(!snapshot||!key)throw Error('보관함이 잠겼습니다.');saving=saving.catch(()=>{}).then(async()=>storeEnvelope(await encrypt(snapshot,key,salt)));await saving;}
async function requireVault(action){if(personal)return action?.();pendingAction=action;const saved=await loadEnvelope();showModal(`<h2>${saved?'로컬 보관함 열기':'나만의 로컬 보관함'}</h2><p>경험·지원서·별표·개인 일정은 이 브라우저에 암호화해 저장합니다.</p><div class="notice warning">비밀번호를 잊으면 복구할 수 없습니다. 브라우저 데이터 삭제에 대비해 설정에서 암호화 백업을 보관하세요.</div><form id="unlock-form"><div class="field"><label for="password">${saved?'비밀번호':'새 비밀번호 (10자 이상)'}</label><input id="password" type="password" autocomplete="${saved?'current-password':'new-password'}" required ${saved?'':'minlength="10"'}></div>${saved?'':'<div class="field"><label for="password2">비밀번호 확인</label><input id="password2" type="password" autocomplete="new-password" required></div>'}<button class="primary" type="submit">${saved?'열기':'보관함 만들기'}</button><p id="unlock-error" class="danger" role="alert"></p></form>`);
 $('#unlock-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const p=$('#password').value;if(!saved&&p!==$('#password2').value)throw Error('비밀번호 확인이 일치하지 않습니다.');const opened=saved?await openEnvelope(saved,p):await newEnvelope(p);if(!saved)await storeEnvelope(opened.envelope);personal=opened.state;vaultKey=opened.key;vaultSalt=opened.salt;const next=pendingAction;closeModal();syncVaultUi();render();await next?.();}catch(err){$('#unlock-error').textContent=err.message;}finally{b.disabled=false;}};
}
$('#vault-button').onclick=async()=>{if(personal){if(dirty&&!confirm('저장하지 않은 편집 내용이 있습니다. 잠글까요?'))return;try{await saving;}catch{toast('저장 실패가 있습니다. 백업 후 다시 시도하세요.');return;}personal=null;vaultKey=null;vaultSalt=null;editorId=null;editorJob=null;dirty=false;closeModal();syncVaultUi();render();}else await requireVault();};
function locked(title){main.innerHTML=header(title)+`<div class="panel empty"><h2>이 컴퓨터의 보관함을 열어주세요</h2><p>개인 자료는 서버에서 불러오지 않습니다.</p><button class="primary" id="open-vault">로컬 보관함 열기</button></div>`;$('#open-vault').onclick=()=>requireVault();}
async function refresh(){const b=$('#refresh');b.disabled=true;try{const r=await fetch('./data/jobs.json',{cache:'no-store'});if(!r.ok)throw Error('공고 데이터를 읽지 못했습니다.');const data=await r.json();if(!Array.isArray(data.jobs)||!Array.isArray(data.sources))throw Error('공고 데이터 형식이 올바르지 않습니다.');feed=data;if(!dirty)render();else toast('공고를 갱신했습니다. 작성 중인 내용은 유지됩니다.');}catch(err){if(!feed.generatedAt)main.innerHTML=header('공고를 불러오지 못했습니다')+`<div class="notice warning">${esc(err.message)} 잠시 후 새로고침해 주세요. 로컬 보관함은 별도로 사용할 수 있습니다.</div>`;else toast(err.message+' 이전 자료를 유지합니다.');}finally{b.disabled=false;}}
$('#refresh').onclick=refresh;
function render(){syncVaultUi();document.querySelectorAll('.sidebar nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${route()}`));if(['domestic','overseas','favorites'].includes(route()))renderJobs();else if(route()==='calendar')renderCalendar();else if(route()==='experiences')renderExperiences();else if(route()==='writer')renderWriter();else if(route()==='documents')renderDocuments();else renderSettings();}
window.addEventListener('hashchange',()=>{dirty=false;render();});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{if(dirty&&!confirm('저장하지 않은 지원서 편집 내용이 있습니다. 이동할까요?'))e.preventDefault();}));
function isStar(id){return personal?.favorites.includes(id)||false;}
async function toggleStar(id){await requireVault(async()=>{const old=[...personal.favorites];personal.favorites=isStar(id)?personal.favorites.filter(x=>x!==id):[...personal.favorites,id];try{await persist();render();}catch(err){personal.favorites=old;toast(err.message);}});}
function jobCard(j){const status=liveStatus(j);return `<article class="job ${isStar(j.id)?'starred':''}"><button class="star ${isStar(j.id)?'on':''}" data-star="${esc(j.id)}" aria-label="${isStar(j.id)?'중요 공고 해제':'중요 공고 지정'}" aria-pressed="${isStar(j.id)}">${isStar(j.id)?'★':'☆'}</button><div><div class="company">${esc(j.company)} · ${esc(countries[j.country]||j.country)}</div><button class="job-title" data-detail="${esc(j.id)}">${esc(j.title)}</button><div class="tags"><span class="tag">${esc(j.category)}</span><span class="tag">${esc(j.level||'지원 수준 확인')}</span><span class="tag ${status}">${statusNames[status]}</span></div></div><div class="job-deadline"><span class="muted">지원 마감</span><br>${esc(dueLabel(j))}</div><div class="job-actions"><button class="small" data-write="${esc(j.id)}">지원서 작성 ↗</button><a href="${esc(safeUrl(j.sourceUrl))}" target="_blank" rel="noopener noreferrer" class="muted">원문 확인 ↗</a></div></article>`;}
function bindJobs(){document.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>toggleStar(b.dataset.star));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showJob(b.dataset.detail));document.querySelectorAll('[data-write]').forEach(b=>b.onclick=()=>startWriting(b.dataset.write));}
function renderJobs(){const mode=route();if(mode==='favorites'&&!personal)return locked('중요 공고');let list=feed.jobs.filter(j=>mode==='favorites'?isStar(j.id):mode==='domestic'?j.country==='KR':j.country!=='KR');const active=list.filter(j=>liveStatus(j)==='open').length;main.innerHTML=header(mode==='domestic'?'국내 공고':mode==='overseas'?'해외 공고':'중요 공고',mode==='overseas'?'영국 · 홍콩 · 싱가포르 · 폴란드 · 일본 | 언어·학위·비자 조건을 확인하세요.':'퀀트 · 자산운용 · ETF · 리스크 · 파생상품평가')+`<div class="stats"><div class="stat"><span>지원 가능 확인</span><strong>${active}</strong></div><div class="stat"><span>조건 확인 필요</span><strong>${list.filter(j=>liveStatus(j)==='review').length}</strong></div><div class="stat"><span>나의 중요 공고</span><strong>${personal?personal.favorites.length:'—'}</strong></div></div><div class="notice">최근 수집 ${esc(stamp(feed.generatedAt))} · 수집 ${feed.sources.filter(s=>s.status==='ok').length}/${feed.sources.length}개 경로 확인. <a href="#settings">수집 범위와 접근 제한 보기 ↗</a>${feed.generatedAt&&Date.now()-new Date(feed.generatedAt)>86400000?' · 새 수집이 필요합니다.':''}</div><div class="filters"><input id="job-search" type="search" placeholder="회사, 직무, 키워드 검색" aria-label="공고 검색" value="${esc(filters.q)}"><select id="category" aria-label="분야"><option value="">모든 분야</option>${categories.map(c=>`<option ${filters.category===c?'selected':''}>${c}</option>`).join('')}</select><select id="status" aria-label="공고 상태">${[['active','미마감 후보 전체'],['open','지원 가능 확인'],['review','조건 확인 필요'],['closed','마감'],['all','보관된 전체']].map(([v,t])=>`<option value="${v}" ${filters.status===v?'selected':''}>${t}</option>`).join('')}</select>${mode==='overseas'?`<select id="country" aria-label="국가"><option value="">모든 국가</option>${Object.entries(countries).filter(([k])=>k!=='KR').map(([k,v])=>`<option value="${k}" ${filters.country===k?'selected':''}>${v}</option>`).join('')}</select>`:''}</div><p class="muted" id="result-count"></p><section class="board" id="job-list" aria-label="채용공고"></section>`;
 const update=()=>{const q=filters.q.toLowerCase();const result=list.filter(j=>(`${j.company} ${j.title} ${j.category}`.toLowerCase().includes(q))&&(!filters.category||j.category===filters.category)&&(!filters.country||mode!=='overseas'||j.country===filters.country)&&(filters.status==='all'||filters.status==='active'?filters.status==='all'||!['closed','excluded'].includes(liveStatus(j)):liveStatus(j)===filters.status)).sort((a,b)=>Number(isStar(b.id))-Number(isStar(a.id))||(a.deadlineDate||'9999').localeCompare(b.deadlineDate||'9999'));$('#result-count').textContent=`${result.length}개 공고 · 날짜가 없는 공고는 마감 확인이 필요합니다.`;$('#job-list').innerHTML=result.map(jobCard).join('')||'<div class="empty">이 조건으로 확인된 공고가 없습니다.<br>수집되지 않은 경로는 수집 현황에서 확인하세요.</div>';bindJobs();};
 $('#job-search').oninput=e=>{filters.q=e.target.value;update();};$('#category').onchange=e=>{filters.category=e.target.value;update();};$('#status').onchange=e=>{filters.status=e.target.value;update();};if($('#country'))$('#country').onchange=e=>{filters.country=e.target.value;update();};update();}
function showJob(id){const j=feed.jobs.find(x=>x.id===id);if(!j)return;showModal(`<div class="eyebrow">${esc(countries[j.country])} · ${esc(j.category)}</div><h2>${esc(j.company)}</h2><h3>${esc(j.title)}</h3><div class="detail-grid">${[['상태',statusNames[liveStatus(j)]],['마감',dueLabel(j)],['지원 수준',j.level||'확인 필요'],['언어',j.languageStatus||'확인 필요'],['비자/취업허가',j.visaStatus||'확인 필요'],['마지막 원문 확인',stamp(j.lastVerifiedAt)]].map(([k,v])=>`<div><small>${k}</small>${esc(v)}</div>`).join('')}</div><div class="notice">${esc(j.evidence||'원문에서 요건을 확인하세요.')}</div><div class="actions"><a href="${esc(safeUrl(j.sourceUrl))}" target="_blank" rel="noopener noreferrer">채용 원문 열기 ↗</a><button id="detail-write" class="primary">지원서 작성</button><button id="detail-event">작성 일정 잡기</button></div>`);$('#detail-write').onclick=()=>{closeModal();startWriting(id);};$('#detail-event').onclick=()=>{closeModal();eventForm(id);};}
function startWriting(id){requireVault(()=>{editorJob=id;editorId=null;dirty=false;if(route()==='writer')renderWriter();else location.hash='writer';});}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();const dated=feed.jobs.filter(j=>j.deadlineDate&&!['closed','excluded'].includes(liveStatus(j)));main.innerHTML=header('지원 캘린더','마감일과 내 작성 일정을 함께 관리합니다.',`<button class="primary" id="add-event">+ 작성 일정</button>`)+`<div class="calendar-tools"><button id="prev-month" aria-label="이전 달">←</button><h2>${y}년 ${m+1}월</h2><button id="next-month" aria-label="다음 달">→</button><button id="this-month">이번 달</button></div><p class="muted">파랑: 공고 마감 · 금색: 중요 공고 · 초록: 내 일정 | 시각 미상인 마감일은 원문을 확인하세요.</p><div class="calendar">${['일','월','화','수','목','금','토'].map(x=>`<div class="weekday">${x}</div>`).join('')}${calendarCells(y,m).map(cell=>`<div class="day ${cell.current?'':'outside'} ${cell.date===dateInZone()?'today':''}"><span class="day-number">${cell.day}</span>${dated.filter(j=>j.deadlineDate===cell.date).map(j=>`<button class="calendar-item ${isStar(j.id)?'favorite':''}" data-detail="${esc(j.id)}">${isStar(j.id)?'★ ':''}${esc(j.company)}<br>${esc(j.category)}</button>`).join('')}${(personal?.events||[]).filter(e=>e.date===cell.date).map(e=>`<button class="calendar-item personal ${e.completed?'done':''}" data-event="${esc(e.id)}">${esc(e.title)}</button>`).join('')}</div>`).join('')}</div><div class="panel"><h2>마감일 미정 · 중요 공고</h2>${feed.jobs.filter(j=>isStar(j.id)&&!j.deadlineDate&&!['closed','excluded'].includes(liveStatus(j))).map(jobCard).join('')||'<p class="muted">별표한 공고 중 마감일이 없는 공고가 여기에 표시됩니다.</p>'}</div>`;$('#prev-month').onclick=()=>{calendarDate=new Date(y,m-1,1);renderCalendar();};$('#next-month').onclick=()=>{calendarDate=new Date(y,m+1,1);renderCalendar();};$('#this-month').onclick=()=>{calendarDate=new Date();renderCalendar();};$('#add-event').onclick=()=>eventForm();bindJobs();document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>eventForm(null,b.dataset.event));}
function eventForm(jobId=null,eventId=null){requireVault(()=>{const old=personal.events.find(x=>x.id===eventId),j=feed.jobs.find(x=>x.id===(old?.jobId||jobId));showModal(`<h2>${old?'일정 수정':'작성 일정 추가'}</h2><form id="event-form"><div class="field"><label for="event-title">일정 이름</label><input id="event-title" required value="${esc(old?.title|| (j?j.company+' 자소서 초안':''))}"></div><div class="field"><label for="event-date">날짜</label><input id="event-date" type="date" required value="${esc(old?.date||dateInZone())}"></div><div class="field"><label for="event-type">종류</label><select id="event-type">${['초안','검토','제출','개인'].map(t=>`<option ${old?.type===t?'selected':''}>${t}</option>`).join('')}</select></div><label class="check-row"><input type="checkbox" id="event-done" ${old?.completed?'checked':''}>완료한 일정</label><div class="actions"><button class="primary" type="submit">로컬에 저장</button>${old?'<button type="button" class="danger" id="event-delete">삭제</button>':''}</div></form>`);$('#event-form').onsubmit=async e=>{e.preventDefault();const item={id:old?.id||uid(),jobId:j?.id||null,title:$('#event-title').value.trim(),date:$('#event-date').value,type:$('#event-type').value,completed:$('#event-done').checked};if(old)personal.events=personal.events.map(x=>x.id===old.id?item:x);else personal.events.push(item);try{await persist();closeModal();render();toast('일정을 저장했습니다.');}catch(err){toast(err.message);}};if(old)$('#event-delete').onclick=async()=>{if(!confirm('이 일정을 삭제할까요?'))return;personal.events=personal.events.filter(x=>x.id!==old.id);await persist();closeModal();render();};});}
function renderExperiences(){if(!personal)return locked('경험 보관함');main.innerHTML=header('경험 보관함','내가 한 일과 성과를 기록하고 여러 지원서에 활용하세요.',`<button id="add-experience" class="primary">+ 경험 추가</button>`)+`<div class="panel">${personal.experiences.map(e=>`<article class="experience-card"><div class="muted">${esc(e.dates||'기간 미입력')}</div><h3>${esc(e.title)}</h3><p>${esc(e.action||e.situation)}</p><div class="tags">${(e.skills||'').split(',').filter(Boolean).map(s=>`<span class="tag">${esc(s.trim())}</span>`).join('')}</div><div class="actions"><button class="small" data-experience="${esc(e.id)}">수정</button></div></article>`).join('')||'<div class="empty">프로젝트, 연구, 인턴, 수업에서의 경험을 추가해 보세요.<br>상황 → 과제 → 행동 → 성과 순서로 정리합니다.</div>'}</div>`;$('#add-experience').onclick=()=>experienceForm();document.querySelectorAll('[data-experience]').forEach(b=>b.onclick=()=>experienceForm(b.dataset.experience));}
function experienceForm(id){const old=personal.experiences.find(x=>x.id===id)||{};showModal(`<h2>${id?'경험 수정':'경험 추가'}</h2><form id="experience-form">${[['title','경험 이름'],['dates','기간'],['skills','역량·기술 (쉼표로 구분)']].map(([k,t])=>`<div class="field"><label for="exp-${k}">${t}</label><input id="exp-${k}" ${k==='title'?'required':''} value="${esc(old[k])}"></div>`).join('')}${[['situation','상황 — 어떤 배경이었나요?'],['task','과제 — 본인이 맡은 역할은?'],['action','행동 — 구체적으로 무엇을 했나요?'],['result','성과 — 확인 가능한 결과는?']].map(([k,t])=>`<div class="field"><label for="exp-${k}">${t}</label><textarea id="exp-${k}" rows="3">${esc(old[k])}</textarea></div>`).join('')}<div class="actions"><button class="primary" type="submit">경험 저장</button>${id?'<button type="button" id="delete-experience" class="danger">삭제</button>':''}</div></form>`);$('#experience-form').onsubmit=async e=>{e.preventDefault();const item={id:id||uid()};['title','dates','skills','situation','task','action','result'].forEach(k=>item[k]=$('#exp-'+k).value.trim());if(id)personal.experiences=personal.experiences.map(x=>x.id===id?item:x);else personal.experiences.push(item);try{await persist();closeModal();render();toast('경험을 저장했습니다.');}catch(err){toast(err.message);}};if(id)$('#delete-experience').onclick=async()=>{if(!confirm('경험을 삭제할까요? 이미 저장한 지원서 본문은 남습니다.'))return;personal.experiences=personal.experiences.filter(x=>x.id!==id);await persist();closeModal();render();};}
function writerData(){return {company:$('#doc-company').value.trim(),role:$('#doc-role').value.trim(),kind:$('#doc-kind').value,country:$('#doc-country').value,question:$('#doc-question').value.trim(),content:$('#doc-content').value,experiences:[...document.querySelectorAll('[name=experience]:checked')].map(c=>personal.experiences.find(e=>e.id===c.value)).filter(Boolean)};}
function renderWriter(){if(!personal)return locked('작성 도우미');const d=personal.documents.find(x=>x.id===editorId),j=feed.jobs.find(x=>x.id===(d?.jobId||editorJob));main.innerHTML=header('작성 도우미','선택한 경험으로 구성하고, 사실을 확인한 뒤 나만의 문장으로 다듬으세요.')+`<div class="split"><div><section class="panel"><h2>지원 정보</h2><div class="field"><label for="doc-company">회사</label><input id="doc-company" value="${esc(d?.company||j?.company)}"></div><div class="field"><label for="doc-role">직무</label><input id="doc-role" value="${esc(d?.role||j?.title)}"></div><div class="field"><label for="doc-country">지원 지역</label><select id="doc-country">${Object.entries(countries).map(([k,v])=>`<option value="${k}" ${(d?.country||j?.country||'KR')===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="doc-kind">문서 종류</label><select id="doc-kind">${['자소서','CV','Cover letter'].map(t=>`<option ${(d?.kind||(j&&j.country!=='KR'?'CV':'자소서'))===t?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label for="doc-question">문항·작성 요청</label><textarea id="doc-question" rows="4" placeholder="문항과 분량, 강조할 역량을 입력하세요.">${esc(d?.question)}</textarea></div></section><section class="panel"><h2>활용할 경험</h2>${personal.experiences.map(e=>`<label class="check-row"><input type="checkbox" name="experience" value="${esc(e.id)}" ${d?.experienceIds?.includes(e.id)?'checked':''}><span>${esc(e.title)}<br><small class="muted">${esc(e.skills)}</small></span></label>`).join('')||'<p class="muted">아직 경험이 없습니다. <a href="#experiences">경험을 먼저 추가하세요.</a></p>'}<div class="actions"><button id="make-outline">초안 구조 만들기</button><button id="copy-prompt">GPT 요청문 복사</button></div><p class="muted">초안 구조는 저장된 경험을 배치하는 기능입니다. GPT 실행 전까지 외부로 전송하지 않습니다.</p></section></div><section class="panel"><div class="page-head"><h2>지원서 편집</h2><span id="char-count" class="muted"></span></div><label for="doc-content">본문</label><textarea id="doc-content" class="editor" placeholder="초안을 구성하거나 기존 자소서·CV를 붙여넣으세요.">${esc(d?.content)}</textarea><div class="actions"><button id="save-doc" class="primary">로컬에 저장</button><button id="gpt-review">GPT로 작성·다듬기</button><button id="download-draft">텍스트 다운로드</button></div><p class="muted" id="save-status">${d?'마지막 저장 '+esc(stamp(d.updatedAt)):'저장 버튼을 눌러야 내 지원서에 보관됩니다.'}</p><p class="muted">GPT 요청문 복사는 ChatGPT에 직접 붙여넣어 사용할 수 있습니다. API 사용은 로컬 실행 화면과 별도 API 키가 필요합니다.</p></section></div>`;
 const count=()=>$('#char-count').textContent=`${Array.from($('#doc-content').value).length.toLocaleString()}자 · 공백 포함`;main.querySelectorAll('input,textarea,select').forEach(e=>e.addEventListener('input',()=>{dirty=true;count();}));count();
 $('#make-outline').onclick=()=>{const data=writerData();if(!data.experiences.length)return toast('활용할 경험을 선택하세요.');if(data.content&&!confirm('본문을 경험 기반 초안 구조로 바꿀까요?'))return;$('#doc-content').value=outline(data);dirty=true;count();};
 $('#copy-prompt').onclick=async()=>{const text=writingPrompt(writerData());try{await navigator.clipboard.writeText(text);toast('요청문을 복사했습니다. ChatGPT에 붙여넣기 전 내용을 확인하세요.');}catch{showModal(`<h2>GPT 요청문</h2><textarea rows="15" aria-label="복사할 요청문">${esc(text)}</textarea>`);}};
 $('#save-doc').onclick=async()=>{const data=writerData();if(!data.company||!data.role||!data.content.trim())return toast('회사, 직무, 본문을 입력하세요.');const old=personal.documents.find(x=>x.id===editorId),item={id:editorId||uid(),jobId:old?.jobId||editorJob||null,company:data.company,role:data.role,kind:data.kind,country:data.country,question:data.question,content:data.content,experienceIds:data.experiences.map(e=>e.id),createdAt:old?.createdAt||now(),updatedAt:now()};if(old)personal.documents=personal.documents.map(x=>x.id===old.id?item:x);else personal.documents.push(item);try{await persist();editorId=item.id;dirty=false;$('#save-status').textContent='저장 완료 · '+stamp(item.updatedAt);toast('이 브라우저의 내 지원서에 저장했습니다.');}catch(err){toast(err.message);}};
 $('#download-draft').onclick=()=>{const d=writerData();download(`${d.company||'지원서'}_${d.kind}.txt`,d.content,'text/plain');};
 $('#gpt-review').onclick=()=>{if(!['127.0.0.1','localhost'].includes(location.hostname)){showModal('<h2>GPT API는 로컬 화면에서 연결합니다</h2><p>API 키를 공개 웹페이지에 넣지 않기 위해 로컬 도우미가 대신 연결합니다. 프로젝트의 README에 있는 로컬 실행 방법을 이용하세요.</p><p>지금은 <strong>GPT 요청문 복사</strong>를 눌러 ChatGPT에서 작성한 뒤 결과를 이 편집기에 붙여넣어 저장할 수 있습니다.</p><p class="muted">Pages와 로컬 화면은 다른 보관함입니다. 설정에서 암호화 백업으로 옮기세요.</p>');return;}const prompt=writingPrompt(writerData());showModal(`<h2>GPT에 보낼 내용 확인</h2><p>아래 내용만 OpenAI API로 전송됩니다. 별도 API 이용 요금이 발생할 수 있습니다. 서버 저장 비활성화를 요청하지만 OpenAI의 정책에 따른 보존이 있을 수 있습니다.</p><textarea id="gpt-prompt" rows="13" aria-label="GPT에 전송할 내용">${esc(prompt)}</textarea><div class="actions"><button id="send-gpt" class="primary">확인한 내용 전송</button></div><p id="gpt-status" role="status" class="muted"></p>`);$('#send-gpt').onclick=async()=>{const b=$('#send-gpt');b.disabled=true;$('#gpt-status').textContent='GPT가 초안을 작성하고 있습니다…';try{const r=await fetch('./api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:$('#gpt-prompt').value}),signal:AbortSignal.timeout(120000)});const data=await r.json();if(!r.ok)throw Error(data.error||'GPT 연결에 실패했습니다.');showModal(`<h2>GPT 제안 검토</h2><textarea id="gpt-result" rows="16" aria-label="GPT가 작성한 제안">${esc(data.text)}</textarea><p class="muted">사실과 수치를 확인하세요. 반영해도 저장 버튼을 누르기 전에는 저장되지 않습니다.</p><button id="apply-gpt" class="primary">편집기에 반영</button>`);$('#apply-gpt').onclick=()=>{if(!$('#doc-content'))return closeModal();$('#doc-content').value=$('#gpt-result').value;dirty=true;count();closeModal();};}catch(err){if($('#gpt-status'))$('#gpt-status').textContent=err.message;}finally{b.disabled=false;}};};
}
function renderDocuments(){if(!personal)return locked('내 지원서');main.innerHTML=header('내 지원서','이 브라우저에 저장한 지원서입니다. 회사·직무별로 찾아 바로 편집하세요.',`<button id="new-document" class="primary">+ 새 지원서</button>`)+`<div class="filters"><input id="document-search" type="search" placeholder="회사, 직무, 문서 종류 검색" aria-label="지원서 검색"></div><div class="panel" id="documents-list"></div>`;const update=()=>{const q=$('#document-search').value.toLowerCase();$('#documents-list').innerHTML=[...personal.documents].filter(d=>`${d.company} ${d.role} ${d.kind}`.toLowerCase().includes(q)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(d=>`<article class="doc-card"><div class="muted">${esc(d.company)} · ${esc(d.kind)} · ${esc(countries[d.country||'KR'])}</div><h3>${esc(d.role)}</h3><p>${esc(d.content.slice(0,140))}${d.content.length>140?'…':''}</p><p class="muted">${esc(stamp(d.updatedAt))}</p><div class="actions"><button data-open-doc="${esc(d.id)}">열기 · 편집</button><button class="danger" data-delete-doc="${esc(d.id)}">삭제</button></div></article>`).join('')||'<div class="empty">저장한 지원서가 없습니다.</div>';document.querySelectorAll('[data-open-doc]').forEach(b=>b.onclick=()=>{editorId=b.dataset.openDoc;editorJob=null;location.hash='writer';});document.querySelectorAll('[data-delete-doc]').forEach(b=>b.onclick=async()=>{if(!confirm('이 지원서를 로컬 보관함에서 삭제할까요?'))return;personal.documents=personal.documents.filter(d=>d.id!==b.dataset.deleteDoc);await persist();update();});};$('#document-search').oninput=update;$('#new-document').onclick=()=>{editorId=null;editorJob=null;location.hash='writer';};update();}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name.replace(/[\\/:*?"<>|]/g,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function renderSettings(){main.innerHTML=header('수집 현황 · 설정','수집되지 않은 경로와 개인 자료 보관 상태를 확인하세요.')+`<div class="panel"><h2>매일 오전 5시 · 한국 시간</h2><p>자동 수집은 별도 예약 작업이 실행합니다. 이 화면의 새로고침은 저장된 공개 데이터를 다시 읽습니다.</p><p class="muted">마지막 수집: ${esc(stamp(feed.generatedAt))} · 실행 환경: 로컬 Codex 예약 작업</p><p class="muted">웹페이지가 닫혀 있어도 예약 작업이 실행되면 Codex에서 알립니다. 컴퓨터나 실행 환경이 이용 가능해야 합니다.</p></div><div class="panel"><h2>개인 자료 백업</h2><p>경험·지원서·별표·일정은 브라우저별로 저장됩니다. 비밀번호를 보관하고 암호화 백업을 별도의 로컬 폴더에 저장하세요.</p><div class="actions"><button id="export-vault">암호화 백업 다운로드</button><button id="import-vault">백업 가져오기</button><button id="persistent-storage">저장 공간 보존 요청</button></div><input id="backup-file" type="file" accept="application/json,.json" hidden><p class="muted">다른 기기·브라우저·사이트 주소에서는 백업을 가져와야 합니다. 암호화는 잠금 해제된 화면이나 기기 자체의 접근까지 차단하지 않습니다.</p></div><div class="panel"><h2>최근 공고 변경</h2>${(feed.changes||[]).slice(-20).reverse().map(c=>{const j=feed.jobs.find(x=>x.id===c.jobId);return `<p class="muted"><span class="updated">${esc({new:'신규',updated:'변경',closed:'마감'}[c.kind]||c.kind)}</span> · ${esc(j?j.company+' / '+j.title:c.jobId)} · ${esc(stamp(c.detectedAt))}</p>`;}).join('')||'<p class="muted">기록된 변경이 없습니다.</p>'}</div><h2>탐색 경로</h2><div class="source-list">${feed.sources.map(s=>`<article class="source-card"><h3><a href="${esc(safeUrl(s.url))}" target="_blank" rel="noopener noreferrer">${esc(s.name)} ↗</a></h3><span class="tag ${s.status==='ok'?'open':'review'}">${esc({ok:'수집 확인',partial:'일부 수집',blocked:'접근 제한',manual:'별도 확인 필요',error:'수집 실패',pending:'미실행'}[s.status]||s.status)}</span><p>${esc(s.reason||'')}</p><p class="muted">${esc(s.coverageLimit||'')}<br>최근 시도 ${esc(stamp(s.lastAttemptAt))}${s.lastSuccessAt?'<br>최근 성공 '+esc(stamp(s.lastSuccessAt)):''}</p></article>`).join('')}</div>`;
 $('#export-vault').onclick=async()=>{const env=await loadEnvelope();if(!env)return toast('먼저 보관함을 만들어주세요.');await saving;download(`career-desk-${dateInZone()}.vault.json`,JSON.stringify(await loadEnvelope()));toast('암호화된 백업을 다운로드했습니다.');};
 $('#import-vault').onclick=()=>$('#backup-file').click();$('#backup-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>14000000)return toast('백업 파일이 너무 큽니다.');let env;try{env=JSON.parse(await f.text());}catch{return toast('JSON 백업 파일이 아닙니다.');}showModal('<h2>암호화 백업 복원</h2><p>백업을 만들 때의 비밀번호를 입력하세요. 복원하면 현재 보관함을 대체합니다.</p><label for="restore-password">백업 비밀번호</label><input id="restore-password" type="password" autocomplete="current-password"><div class="actions"><button id="restore" class="primary">검증하고 복원</button></div><p id="restore-error" class="danger" role="alert"></p>');$('#restore').onclick=async()=>{try{const opened=await openEnvelope(env,$('#restore-password').value);if(!confirm('백업이 확인되었습니다. 현재 로컬 자료를 이 백업으로 대체할까요?'))return;await saving;await storeEnvelope(env);personal=opened.state;vaultKey=opened.key;vaultSalt=opened.salt;closeModal();render();toast('백업을 복원했습니다.');}catch(err){$('#restore-error').textContent=err.message;}};};
 $('#persistent-storage').onclick=async()=>{if(!navigator.storage?.persist)return toast('이 브라우저에서는 지원하지 않습니다.');toast(await navigator.storage.persist()?'저장 공간 보존이 허용되었습니다. 백업도 유지하세요.':'브라우저가 보존 요청을 허용하지 않았습니다. 백업을 이용하세요.');};
}
$('#today').textContent=new Intl.DateTimeFormat('ko-KR',{dateStyle:'full',timeZone:'Asia/Seoul'}).format(new Date());
refresh();
const toolsLifecycle=registerPublicTools(document.modelContext,()=>feed.jobs,showJob);
window.addEventListener('pagehide',()=>toolsLifecycle?.abort(),{once:true});
